name: "Volta PNPM Install"
description: "This configures the environment for Volta."
runs:
  using: "composite"
  steps:
    - name: Install Volta
      uses: volta-cli/action@v4
    - name: Install node via Volta # pnpm install doesn't seem to work otherwise, but it also doesn't seem to actuall "install" node; it seems to use the same Node
      shell: bash
      run: volta install node
    - name: Install pnpm via Volta
      run: volta install pnpm
      # Set up environment for caching
    - name: Get pnpm store directory
      shell: bash
      run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
    - uses: actions/cache@v4
      name: Setup pnpm cache
      with:
        path: ${{ env.STORE_PATH }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - run: volta run pnpm install