name: Javascript CI (Volta + pnpm via volta)
on:
  - push
permissions:
  actions: write
  checks: write
  contents: read
  issues: write
  pull-requests: write
  id-token: write
jobs:
  infra:
    uses: mechwire/tf-state-remote-backend/.github/workflows/tf.yml@make-workflow-reusable
    secrets: inherit
    with:
      ref: make-workflow-reusable
  deploy:
    needs:
      - infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Volta
        uses: volta-cli/action@v4
      - name: Install node via Volta
        shell: bash
        run: volta install node
      - name: Install pnpm via Volta
        run: volta install pnpm
      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - run: volta run pnpm install
      - run: volta run pnpm test
      - run: volta run pnpm build

